Update VerificationHost#waitFor to use TestContext
Previously, waitFor logic has implemented in VerificationHost and
TimeoutException thrown by waitFor only contains user specified
message and stack trace.

In this commit, waitFor now uses TestContext, and original exception
added as a suppressed exception. Also, no more "throws Throwable".
TestContext has also changed to accept lambda performed before
condition check(latch#await).
Ideally, waitFor should be implemented in TestContext, but put it as
future TODO.

Sample messages (formatted):

* timeout

  java.util.concurrent.TimeoutException: my wait-for message

  at ...VerificationHost.waitFor(VerificationHost.java:3371)
  ...
  Suppressed: java.util.concurrent.TimeoutException: TestContext has
      expired. [start=1471395317344(2016-08-16T17:55:17.344),
      expire=1471395318344(2016-08-16T17:55:18.344),
      durationGiven=PT1S, durationActual=PT1.001S,
      countAtInit=1, countAtAwait=1, countNow=0] at
      ...TestContext.lambda$await$40(TestContext.java:129)
      ...

* waitFor throws exception

java.lang.IllegalStateException: waitFor check logic raised exception

  at ...VerificationHost.waitFor(VerificationHost.java:3377)
  ...
    Suppressed: java.lang.RuntimeException: My raised exception
        at ...TestExampleTaskService.lambda$test$1
                            (TestExampleTaskService.java:192)
        at ...VerificationHost.lambda$waitFor$38
                            (VerificationHost.java:3363)

Change-Id: Ib836828f9344cd14a1fd6e6a9ed8b9e26b8ffdc8